const DataArray = [
    {
      logoSrc: require('@/assets/MainLogo.png'),
      name: "FC APOZH",
      matches: 3,
      wins: 2,
      draws: 0,
      losses: 1,
      goalsFor: 11,
      goalsAgainst: 4,
      points: 6,
    },
    {
      logoSrc: require('@/assets/AngelCity.png'),
      name: "FC Angel City",
      matches: 3,
      wins: 3,
      draws: 0,
      losses: 0,
      goalsFor: 19,
      goalsAgainst: 3,
      points: 9,
    },
    {
      logoSrc: require('@/assets/turbo.png'),
      name: "FC Turbo",
      matches: 3,
      wins: 3,
      draws: 0,
      losses: 0,
      goalsFor: 18,
      goalsAgainst: 4,
      points: 9,
    },
    {
      logoSrc: require('@/assets/Prometeus (2).png'),
      name: "Прометей",
      matches: 2,
      wins: 1,
      draws: 0,
      losses: 1,
      goalsFor: 5,
      goalsAgainst: 4,
      points: 3,
    },
    {
      logoSrc: require('@/assets/ESPADA.png'),
      name: "ФК Еспада",
      matches: 3,
      wins: 1,
      draws: 0,
      losses: 2,
      goalsFor: 7,
      goalsAgainst: 8,
      points: 3,
    },
    {
      logoSrc: require('@/assets/Kryizy.jpg'),
      name: "Круїзи",
      matches: 2,
      wins: 1,
      draws: 0,
      losses: 1,
      goalsFor: 2,
      goalsAgainst: 2,
      points: 3
    },
    {
      logoSrc: require('@/assets/Goat.png'),
      name: "FC GOAT",
      matches: 3,
      wins: 0,
      draws: 0,
      losses: 3,
      goalsFor: 2,
      goalsAgainst: 20,
      points: 0
    },
    {
      logoSrc: require('@/assets/Tornado.png'),
      name: "Tornado",
      matches: 3,
      wins: 1,
      draws: 0,
      losses: 2,
      goalsFor: 6,
      goalsAgainst: 10,
      points: 3
    },
    {
      logoSrc: require('@/assets/ECF.png'),
      name: "ECF",
      matches: 3,
      wins: 3,
      draws: 0,
      losses: 0,
      goalsFor: 11,
      goalsAgainst: 2,
      points: 9,
    },
    {
      logoSrc: require('@/assets/QM.png'),
      name: "Question Mark",
      matches: 3,
      wins: 0,
      draws: 0,
      losses: 3,
      goalsFor: 8,
      goalsAgainst: 20,
      points: 0,
    },
    {
    logoSrc: require('@/assets/fortuna.png'),
    name: "AFC Fortuna Kyiv",
    matches: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 17,
    goalsAgainst: 3,
    points: 7,
      },
      {
    logoSrc: require('@/assets/Calipso.png'),
    name: "FC ALP INDUSTRIYA",
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 7,
    goalsAgainst: 10,
    points: 3,
      },
      {
    logoSrc: require('@/assets/Nyvky.png'),
    name: "AFC Nyvky",
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 5,
    goalsAgainst: 16,
    points: 3,
      },
      {
    logoSrc: require('@/assets/Kvartal.png'),
    name: "FC Kvartal",
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 5,
    goalsAgainst: 16,
    points: 3,
      },
      {
    logoSrc: require('@/assets/numancia.png'),
    name: "Numancia-2",
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 10,
    goalsAgainst: 11,
    points: 3,
      },
      {
    logoSrc: require('@/assets/Secur.png'),
    name: "Secur",
    matches: 1,
    wins: 0,
    draws: 1,
    losses: 0,
    goalsFor: 1,
    goalsAgainst: 1,
    points: 1,
      },
      
    ];
    
    export { DataArray };